# Generated by Django 5.2.7 on 2025-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_direccion_latitud_direccion_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='cedula_vehiculo',
            field=models.ImageField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('BICI', 'Bicicleta'), ('MOTO', 'Motocicleta')], default='BICI', max_length=10),
        ),
    ]
