# Generated by Django 5.2.7 on 2025-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recetamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='latitud_fija',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud fija para pruebas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='longitud_fija',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud fija para pruebas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='ubicacion_fija',
            field=models.BooleanField(default=False, help_text='Si está marcado, usa ubicación fija en lugar de GPS'),
        ),
    ]
