# Generated by Django 5.2.7 on 2025-10-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repartidor_latitud_fija_repartidor_longitud_fija_and_more'),
        ('core', '0005_producto_imagen'),
    ]

    operations = [
    ]
