# Generated by Django 5.2.7 on 2025-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_repartidor_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
