# Generated by Django 5.2.7 on 2025-10-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recetamedica'),
        ('core', '0005_producto_imagen'),
    ]

    operations = [
    ]
