# Generated by Django 5.2.7 on 2025-10-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pedido_estado_pedidorechazado'),
        ('core', '0008_alter_farmacia_user_alter_pedido_estado'),
    ]

    operations = [
    ]
