# Generated by Django 5.2.7 on 2025-11-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251030_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Transferencia'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
