# Generated by Django 5.2.7 on 2025-11-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_comprobante_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('DOMICILIO', 'Envío a domicilio'), ('RETIRO', 'Retiro en farmacia')], default='DOMICILIO', max_length=20, verbose_name='Tipo de Entrega'),
        ),
    ]
