# Generated by Django 5.2.7 on 2025-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del repartidor', null=True),
        ),
    ]
